# Generated by Django 5.1.6 on 2025-03-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pin',
            field=models.CharField(default='000000', max_length=50),
        ),
    ]
