# Generated by Django 5.1.6 on 2025-03-11 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='pack',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
